site_name: ИНФОРМАЦИОННЫЙ ПОРТАЛ НИЦ "Курчатовский институт" - НИИСИ
theme:
  name: material
  language: ru
  features:
      - navigation.instant
      - navigation.tabs
      - content.tabs.link
   
  palette:
    - scheme:  default
      primary: indigo
      accent:  blue



plugins:
  - search
  - encryptcontent:
      password_file: 'passwords.yml'
      title_prefix: ''
      summary: ''
      remember_keys: true
      remember_password: true
      esm: true # ('Эта настройка помогла при появлении страницы с запросом пароля на милисекунду')


