site_name: ИНФОРМАЦИОННЫЙ ПОРТАЛ НИЦ "Курчатовский институт" - НИИСИ
theme:
  name: material
  language: ru
  features:
      - navigation.instant
      - navigation.tabs
      - content.tabs.link
   
  palette:
    - scheme:  default
      primary: indigo
      accent:  blue



plugins:
  - search
