site_name: ИНФОРМАЦИОННЫЙ ПОРТАЛ НИЦ "Курчатовский институт" - НИИСИ
theme:
  name: material
  language: ru
  features:
      - navigation.instant
      - navigation.tabs
      - content.tabs.link
   
  palette:
    - scheme:  default
      primary: indigo
      accent:  blue



plugins:
  - search
  - encryptcontent:
      password_inventory:
        secret:
          # Берём пароль из переменной окружения ENCRYPT_PASSWORD
          # Если её нет, используем fallback (опционально)
          dorokhov: !ENV NIISI_PASS
      title_prefix: ''
      summary: ''
      remember_keys: true
      remember_password: true
      esm: true # ('Эта настройка помогла при появлении страницы с запросом пароля на милисекунду')


