name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        env:
          NIISI_PASS: ${{ secrets.NIISI_PASS }}
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-encryptcontent-plugin
      - run: mkdocs gh-deploy --force
    



#       - run: pip install mkdocs-material 
#       - run: pip install mkdocs-encryptcontent-plugin
#       - run: mkdocs build  # Сначала сборка с передачей переменной
#         env:
#           NIISI_PASS: ${{ secrets.NIISI_PASS }}
#       - run: mkdocs gh-deploy --force  # Затем деплой
#         env:
#           NIISI_PASS: ${{ secrets.NIISI_PASS }}